experiment:
  name: test03
  mode: single
  output_dir: experiments

data:
  absolute_path: /Users/kuba/Documents/data/Raw/pt_ekyn_500hz
  script_name: EEGDataScript

  split_type: train,dev,test
  split_ratios: [0.8, 0.1, 0.1]
  shuffle: True
  seed: 69

  input_size: 5000
  input_channels: 1
  output_size: 3
  num_classes: 3

model:
  architecture: simple mlp
  absolute_path: /Users/kuba/projects/ml/tests/sample_model.py

parameters:
  param: none

training:
  epochs: 5
  train_batch_size: 128
  test_batch_size: 512

  optimizer: Adam
  learning_rate: 0.001
  criterion: CrossEntropyLoss

  device: cpu

  save_full_model: True
  best_f1: True
  best_loss: True
  early_stopping: False
  early_stopping_patience: 10
  early_stopping_monitor: dev_loss